#spring.ldap.embedded:
#      ldif: classpath:test-server.ldif
#      base-dn: dc=springframework,dc=org
#      port: 636
ad:
  domain: auto0.nifi.ml
  url: ldaps://10.216.20.184:636
  authority.admintool: ZeppelinAdmins
https.port: 8443
keystore:
  file: classpath:security/keystore.jks
  password: 123qwe
  type: JKS
truststore:
  file: classpath:security/truststore.jks
  password: truststore